import sys
import json
import subprocess
import time
import ctypes
import ctypes.wintypes

import psutil
import comtypes
from comtypes import GUID, COMMETHOD, IUnknown


def get_all_windows_apps():
    """Queries the Windows Start Menu index to map friendly names to launch targets."""
    app_map = {}
    normalized_seen = {}

    ps_command = (
        "Get-StartApps | ForEach-Object { "
        'if ($_.AppId) { echo "$($_.Name)||$($_.AppId)" } '
        "}"
    )

    try:
        startupinfo = subprocess.STARTUPINFO()
        startupinfo.dwFlags |= subprocess.STARTF_USESHOWWINDOW

        result = subprocess.run(
            ["powershell", "-Command", ps_command],
            capture_output=True,
            text=True,
            check=True,
            startupinfo=startupinfo,
        )

        for line in result.stdout.splitlines():
            if "||" in line:
                friendly_name, app_id = line.split("||", 1)
                name = friendly_name.strip()
                name_lower = name.lower()

                norm_name = "".join(c for c in name_lower if c.isalnum())

                if norm_name not in normalized_seen:
                    is_url = app_id.startswith("http")
                    if is_url:
                        continue
                    if ":" in app_id and not app_id.startswith("{"):
                        app_map[name_lower] = app_id
                    else:
                        app_map[name_lower] = f"shell:AppsFolder\\{app_id}"

                    normalized_seen[norm_name] = name_lower
                else:
                    existing_key = normalized_seen[norm_name]
                    if len(name_lower) < len(existing_key):
                        launch_path = app_map.pop(existing_key)
                        app_map[name_lower] = launch_path
                        normalized_seen[norm_name] = name_lower

    except Exception as e:
        print(f"Error indexing apps: {e}", file=sys.stderr)

    return app_map


# --- Launch targets come in three shapes from get_all_windows_apps():
#
#   1. A plain filesystem path ("C:\...\App.exe" or ".cmd" / ".msc" / ...).
#   2. "shell:AppsFolder\{GUID}\...\App.exe" -- a Start Menu shortcut to a
#      real exe, just addressed through the shell namespace.
#   3. "shell:AppsFolder\<AUMID>" -- a packaged (UWP/MSIX) or AUMID-registered
#      app (Discord, Chrome, Electron apps, ...). There is no exe path here;
#      Explorer launches these via the Application Activation Manager.
#
# (1) and (2) go through ShellExecuteEx, which hands back a process handle we
# can read a PID from directly. (3) goes through the Activation Manager COM
# API, which returns a PID synchronously as part of the call.
#
# Neither PID is trustworthy on its own: both can name a short-lived launcher
# stub (a single-instance app redirecting activation to an already-running
# window, or a bootstrapper that hands off to a child process and exits).
# _resolve_pid() confirms the candidate is still alive a moment later, and
# if it isn't, falls back to spotting the real process by diffing which
# visible-window-owning PIDs exist before vs. after the launch.
# Generated by Claude Sonnet 5: Medium

SEE_MASK_NOCLOSEPROCESS = 0x00000040
SEE_MASK_FLAG_NO_UI = 0x00000400
SW_SHOWNORMAL = 1
SW_SHOWNOACTIVATE = 4  # visible, keeps current foreground window active


class SHELLEXECUTEINFOW(ctypes.Structure):
    _fields_ = [
        ("cbSize", ctypes.wintypes.DWORD),
        ("fMask", ctypes.wintypes.ULONG),
        ("hwnd", ctypes.wintypes.HWND),
        ("lpVerb", ctypes.wintypes.LPCWSTR),
        ("lpFile", ctypes.wintypes.LPCWSTR),
        ("lpParameters", ctypes.wintypes.LPCWSTR),
        ("lpDirectory", ctypes.wintypes.LPCWSTR),
        ("nShow", ctypes.c_int),
        ("hInstApp", ctypes.wintypes.HINSTANCE),
        ("lpIDList", ctypes.c_void_p),
        ("lpClass", ctypes.wintypes.LPCWSTR),
        ("hkeyClass", ctypes.wintypes.HKEY),
        ("dwHotKey", ctypes.wintypes.DWORD),
        ("hIcon", ctypes.wintypes.HANDLE),
        ("hProcess", ctypes.wintypes.HANDLE),
    ]


def _is_aumid_target(target):
    """True for shell:AppsFolder\\<AUMID> entries (no exe path underneath)."""
    prefix = "shell:appsfolder\\"
    if not target.lower().startswith(prefix):
        return False
    return not target[len(prefix) :].startswith("{")


def _shell_execute(target, background):
    """Launches a filesystem path or shell: item, returning a PID if we can."""
    shell32 = ctypes.windll.shell32
    kernel32 = ctypes.windll.kernel32

    sei = SHELLEXECUTEINFOW()
    sei.cbSize = ctypes.sizeof(sei)
    sei.fMask = SEE_MASK_NOCLOSEPROCESS | SEE_MASK_FLAG_NO_UI
    sei.lpVerb = "open"
    sei.lpFile = target
    sei.nShow = SW_SHOWNOACTIVATE if background else SW_SHOWNORMAL

    if not shell32.ShellExecuteExW(ctypes.byref(sei)):
        return None, kernel32.GetLastError()

    pid = None
    if sei.hProcess:
        pid = kernel32.GetProcessId(sei.hProcess)
        kernel32.CloseHandle(sei.hProcess)
    return pid, None


class IApplicationActivationManager(IUnknown):
    _iid_ = GUID("{2E941141-7F97-4756-BA1D-9DECDE894A3D}")
    _methods_ = [
        COMMETHOD(
            [],
            ctypes.HRESULT,
            "ActivateApplication",
            (["in"], ctypes.c_wchar_p, "appUserModelId"),
            (["in"], ctypes.c_wchar_p, "arguments"),
            (["in"], ctypes.c_int, "options"),
            (["out"], ctypes.POINTER(ctypes.wintypes.DWORD), "processId"),
        ),
    ]


CLSID_ApplicationActivationManager = GUID("{45BA127D-10A8-46EA-8AB7-56EA9078943C}")


def _activate_aumid(aumid):
    """Launches a packaged/AUMID-registered app via the Activation Manager.

    This is how Explorer itself launches shell:AppsFolder\\<AUMID> entries, and
    it is the only way to get a real PID back for them -- ShellExecuteEx hands
    these off to the shell asynchronously and returns no process handle.
    """
    comtypes.CoInitialize()
    try:
        manager = comtypes.CoCreateInstance(
            CLSID_ApplicationActivationManager,
            interface=IApplicationActivationManager,
            clsctx=comtypes.CLSCTX_LOCAL_SERVER,
        )
        return manager.ActivateApplication(aumid, None, 0)
    finally:
        comtypes.CoUninitialize()


def _pid_owns_visible_window(pid):
    user32 = ctypes.windll.user32
    owns = []

    @ctypes.WINFUNCTYPE(ctypes.c_bool, ctypes.wintypes.HWND, ctypes.wintypes.LPARAM)
    def callback(hwnd, _lparam):
        if not user32.IsWindowVisible(hwnd) or user32.GetWindowTextLengthW(hwnd) == 0:
            return True
        owner_pid = ctypes.wintypes.DWORD()
        user32.GetWindowThreadProcessId(hwnd, ctypes.byref(owner_pid))
        if owner_pid.value == pid:
            owns.append(True)
            return False
        return True

    user32.EnumWindows(callback, 0)
    return bool(owns)


def _new_visible_window_pid(before_pids, start_time, timeout):
    """Finds a PID that owns a visible window, wasn't running before the
    launch, and was created after it started -- used when the PID a launch
    API handed us turns out to have been a short-lived stub."""
    user32 = ctypes.windll.user32
    found = []

    @ctypes.WINFUNCTYPE(ctypes.c_bool, ctypes.wintypes.HWND, ctypes.wintypes.LPARAM)
    def callback(hwnd, _lparam):
        if not user32.IsWindowVisible(hwnd) or user32.GetWindowTextLengthW(hwnd) == 0:
            return True
        owner_pid = ctypes.wintypes.DWORD()
        user32.GetWindowThreadProcessId(hwnd, ctypes.byref(owner_pid))
        pid = owner_pid.value
        if pid in before_pids:
            return True
        try:
            if psutil.Process(pid).create_time() >= start_time - 1:
                found.append(pid)
        except psutil.NoSuchProcess:
            pass
        return True

    deadline = time.time() + timeout
    while time.time() < deadline and not found:
        user32.EnumWindows(callback, 0)
        if not found:
            _pump_sleep(0.3)
    return found[0] if found else None


EVENT_SYSTEM_FOREGROUND = 0x0003
WINEVENT_OUTOFCONTEXT = 0x0000
OBJID_WINDOW = 0
PM_REMOVE = 0x0001

WinEventProcType = ctypes.WINFUNCTYPE(
    None,
    ctypes.wintypes.HANDLE,
    ctypes.wintypes.DWORD,
    ctypes.wintypes.HWND,
    ctypes.c_long,
    ctypes.c_long,
    ctypes.wintypes.DWORD,
    ctypes.wintypes.DWORD,
)


class _MSG(ctypes.Structure):
    _fields_ = [
        ("hwnd", ctypes.wintypes.HWND),
        ("message", ctypes.wintypes.UINT),
        ("wParam", ctypes.wintypes.WPARAM),
        ("lParam", ctypes.wintypes.LPARAM),
        ("time", ctypes.wintypes.DWORD),
        ("pt_x", ctypes.c_long),
        ("pt_y", ctypes.c_long),
    ]


def _force_foreground(hwnd):
    """SetForegroundWindow from a background process, via the standard
    AttachThreadInput workaround (Windows otherwise refuses the call)."""
    user32 = ctypes.windll.user32
    kernel32 = ctypes.windll.kernel32
    current = user32.GetForegroundWindow()
    if current == hwnd:
        return
    this_thread = kernel32.GetCurrentThreadId()
    owner_pid = ctypes.wintypes.DWORD()
    fg_thread = user32.GetWindowThreadProcessId(current, ctypes.byref(owner_pid))
    user32.AttachThreadInput(fg_thread, this_thread, True)
    user32.SetForegroundWindow(hwnd)
    user32.AttachThreadInput(fg_thread, this_thread, False)


def _pump_sleep(seconds):
    """time.sleep() that also drains this thread's message queue. A WinEvent
    hook installed with WINEVENT_OUTOFCONTEXT only fires when its owning
    thread pumps messages -- a plain time.sleep() would let events pile up
    unprocessed until we happen to check again, which is exactly the poll
    gap we're trying to avoid. Safe to call even with no hook installed."""
    user32 = ctypes.windll.user32
    msg = _MSG()
    deadline = time.time() + seconds
    while time.time() < deadline:
        while user32.PeekMessageW(ctypes.byref(msg), None, 0, 0, PM_REMOVE):
            user32.TranslateMessage(ctypes.byref(msg))
            user32.DispatchMessageW(ctypes.byref(msg))
        time.sleep(0.005)


def _install_foreground_guard(prev_hwnd):
    """Starts reasserting prev_hwnd as the foreground window the instant
    anything else takes it, via the EVENT_SYSTEM_FOREGROUND system event
    rather than polling (which always leaves a visible flicker).

    Must be installed BEFORE the app is launched: nothing else changes
    foreground after the launched app grabs and keeps it, so a hook started
    afterward has no further steal event left to react to -- it would just
    watch a settled, already-stolen foreground forever. Caller must keep
    pumping messages (see _pump_sleep) for the hook to fire, and must pass
    the returned guard to _uninstall_foreground_guard when done."""
    if not prev_hwnd:
        return None
    user32 = ctypes.windll.user32

    @WinEventProcType
    def callback(_hook, _event, hwnd, id_object, _id_child, _thread, _event_time):
        if id_object == OBJID_WINDOW and hwnd and hwnd != prev_hwnd:
            _force_foreground(prev_hwnd)

    hook = user32.SetWinEventHook(
        EVENT_SYSTEM_FOREGROUND,
        EVENT_SYSTEM_FOREGROUND,
        None,
        callback,
        0,
        0,
        WINEVENT_OUTOFCONTEXT,
    )
    if not hook:
        return None
    return hook, callback  # keep `callback` alive -- ctypes won't hold a ref to it


def _uninstall_foreground_guard(guard):
    if guard:
        ctypes.windll.user32.UnhookWinEvent(guard[0])


def _resolve_pid(candidate_pid, before_pids, start_time):
    """Confirms candidate_pid survived launch; otherwise hunts for the real
    process by spotting a new visible window that appeared in its place."""
    if candidate_pid:
        settle_deadline = time.time() + 1.5
        while time.time() < settle_deadline:
            if not psutil.pid_exists(candidate_pid):
                break
            if _pid_owns_visible_window(candidate_pid):
                return candidate_pid  # confirmed: it's the real, visible app
            _pump_sleep(0.2)
        else:
            return candidate_pid  # never got a window, but never died either

    return (
        _new_visible_window_pid(before_pids, start_time, timeout=5.0) or candidate_pid
    )


def open_app(app_name, background=False):
    if not app_name:
        print(
            'Error: Missing required argument \'app\' (e.g. {"app": "Notepad"}).',
            file=sys.stderr,
        )
        return

    app_map = get_all_windows_apps()
    target = next(
        (path for name, path in app_map.items() if name.lower() == app_name.lower()),
        None,
    )

    if not target:
        print(f"App '{app_name}' not found in system index.", file=sys.stderr)
        return

    before_pids = set(psutil.pids())
    start_time = time.time()
    prev_hwnd = ctypes.windll.user32.GetForegroundWindow() if background else None
    guard = _install_foreground_guard(prev_hwnd) if background else None
    note = ""
    used_com_activation = False

    if _is_aumid_target(target):
        aumid = target[len("shell:appsfolder\\") :]
        try:
            pid = _activate_aumid(aumid)
            used_com_activation = True
        except comtypes.COMError as e:
            print(
                f"Activation Manager failed for {app_name} ({e}), falling back to shell open.",
                file=sys.stderr,
            )
            pid, err = _shell_execute(target, background)
            if pid is None and err:
                print(f"Failed to launch {app_name} (Error {err})", file=sys.stderr)
                return
    else:
        pid, err = _shell_execute(target, background)
        if pid is None and err:
            print(f"Failed to launch {app_name} (Error {err})", file=sys.stderr)
            return

    pid = _resolve_pid(pid, before_pids, start_time)

    if background:
        if used_com_activation:
            # The Activation Manager gives packaged apps no way to suppress
            # activation -- reclaiming focus would just fight the OS forever.
            note = " (packaged apps always take focus on activation -- that's an OS limitation, not a failed launch)"
        else:
            _pump_sleep(1.0)  # trailing buffer in case the steal lands late
        _uninstall_foreground_guard(guard)

    mode = " in background" if background else ""
    pid_str = str(pid) if pid else "unknown"
    print(f"Launched {app_name}{mode}. PID: {pid_str}{note}")


def generate_context():
    """Generates the dynamic LLM context based on the current system state."""
    app_map = get_all_windows_apps()
    apps_str = ", ".join(app_map.keys())

    context = {
        "actor": f"""
## App Launcher
Launch any installed app directly instead of navigating the Start Menu.

Installed apps: [{apps_str}]

Action: {{"action": "open_app", "app": "<name from the list above>", "background": false}}

- `background: true` opens the app without stealing focus, and still returns its real PID for DirectAppControl. Packaged/Store apps (Calculator, Notepad, most UWP apps) always take focus regardless of this flag -- that's an OS limitation, not a bug; treat the launch as successful anyway.
- Only launch apps from the list above; if the target isn't listed, use the web instead.
- Match names loosely (e.g. "Chrome" -> "Google Chrome") using your judgement.
- A launch is done once this action reports success -- don't also try the Start Menu or the taskbar.
- On failure, don't retry blindly: check the Taskbar for an already-running instance first, and if several versions exist, pick the one that best fits the task.
""",
    }

    print(json.dumps(context))


if __name__ == "__main__":
    if "--generate" in sys.argv:
        generate_context()
        sys.exit(0)

    try:
        args = json.loads(sys.argv[1])
    except (IndexError, json.JSONDecodeError):
        print(
            'Error: Invalid or missing JSON arguments provided to skill, The skill takes JSON as its parameters: {"open_app": "appname"}',
            file=sys.stderr,
        )
        sys.exit(1)

    app = args.get("app") or args.get("app_name")
    background = args.get("background", False)

    open_app(app, background)
